nome=str(input('\nEntre com nome: '))
print(f'\nTodo nome: {nome}')
print(f'\nPrimeiro caractere: {nome[0]}')
print(f'\nÚltimo caractere: {nome[-1]}')
print(f'\nPrimeiro ao terceiro caractere: {nome[0:3]}')
print(f'\nQuarto caractere: {nome[3]}')
print(f'\nTodos menos o primeiro: {nome[1:]}')
print(f'\nOs dois últimos: {nome[-2:]}')
print('\n')